### ISSUE TITLE
Trying to understand the demo

### ISSUE THREAD

**Issue by greggman** [xcfox/react-tile-pane#1]
This library looks amazing! Thank you for making it

I'm trying to understand the demo. In particular I'd like to make pane manager that functions like say VSCode where you can drag panes around, doc them, etc. that seems like what your library does.

One thing I don't get is how I disassocaite the name used to identify a pane from the name displayed. I need multiple panes with the same name. I guess I can try to create my own tabbar like the left-bar example but I see it's reaching pretty deep into the src of the library.

```
import {
  createTilePanes,
  DraggableTitle,
  TileBranchSubstance,
  TileContainer,
  TileProvider,
  useGetRootNode,
} from '../../../components'
```

Is that the direction I should go or is there a simpler way to show a tab name different from its id?

**Comment by xcfox** [comment]
You may need to implement `TabsBarConfig` yourself, as is done in [left-bar example](https://github.com/xcfox/react-tile-pane/blob/main/src/App/demo/left-tab/tab-bar/index.tsx).
Try using interface `TabsBarConfig`, `TabBarPropsWithAction`, It might look like this:
```tsx
import {
  DraggableTitle,
  TabBarPropsWithAction,
  TabsBarConfig,
} from 'react-tile-pane'

const TabBar: React.FC<TabBarPropsWithAction> = ({ tabs, onTab, action }) => {
  return (
    <div style={styles.tabBar}>
      <div>
        {tabs.map((tabId, i) => (
          <DraggableTitle
            style={i === onTab ? styles.tabTitleOn : styles.tabTitle}
            name={tabId}
            key={tabId}
            onClick={() => action.switchTab(i)}
          >
            {/* Here you get the tabId, which can be transformed into the name used for the display */}
          </DraggableTitle>
        ))}
      </div>
      <div onClick={() => action.closeTab(onTab)} style={styles.closeButton}>
        ×
      </div>
    </div>
  )
}

export const tabBarConfig: TabsBarConfig = {
  render: TabBar,
  thickness,
  position: 'left',
  preBox: {
    isRow: false,
    isReverse: false,
  },
}
```
Then pass `tabBarConfig` to `TileProvider`:
```tsx
<TileProvider tabBar={tabBarConfig}>
  <TileContainer />
</TileProvider>
```

Hope this helps with your confusion.

**Comment by greggman** [comment]
Thanks! I will give it a try
