### ISSUE TITLE
How do pass through props to the individual panes?

### ISSUE THREAD

**Issue by greggman** [xcfox/react-tile-pane#2]
I didn't see anything in the samples showing how to get data to the panes.

I tried to workaround this by associating data by name in a context, then each pane can get that data by its name from the context. That works, the data makes it down to the component, but, the panes don't re-render when the parent renders.

In other words, I effectively have

```
<App>
    <TileProvider>
        <TileContainer>
           // these exist indirectly via TileProvider paneList
           <Arbutus />
           <Apple />
        <TileContainer/>
    </TileProvider>
</App>
```

But if do something that makes `<App>` re-render I see react call `TileProvider` and `TileContainer` but it never calls `Arbutus` nor `Apple`

How did you imagine in working? In your examples it appears the components in the panes are static (created just once at init time).

**Comment by xcfox** [comment]
In order to share data between panes, [react context](https://reactjs.org/docs/context.html) is a good way, I would rather suggest using some state management tools such as [valtio](https://github.com/pmndrs/valtio), [zustand](https://github.com/pmndrs/zustand), [recoil](https://github.com/facebookexperimental/Recoil).
Here I have written a simple demo using context: https://codesandbox.io/s/react-pane-702905?file=/src/App.js

> the panes don't re-render when the parent renders.

Yes, this is done to avoid unnecessary re-render. It use [React.useMemo](https://reactjs.org/docs/hooks-reference.html#usememo) to keep the panes.

When dragging the `StretchBar` to change the size of the pane, it will be quite stuttered if the re-render of `TileContainer` drives the re-render of panes.

**Comment by greggman** [comment]
Thank you so much for the example.

I guess I don't understand react or at least `React.useMemo` in this case.

I found my issue. It's that the object I was passing for my context never changes but it's properties do. So for example imagine I did this

```
import React, { useContext } from "react";
import { render } from "react-dom";
import "./styles.css";

const MyContext = React.createContext();

const Foo = () => {
  const context = useContext(MyContext);

  return (
    <button
      onClick={() => {
        context.setState({ count: context.state.count + 1 });
      }}
    >
      inc
    </button>
  );
};

const Bar = () => {
  const context = useContext(MyContext);

  return <div>count: {context.state.count}</div>;
};

export default class App extends React.Component {
  constructor() {
    super();

    this.state = { count: 1 };
    this.value = {
      setState: (...args) => this.setState(...args)
    };
  }
  render() {
    this.value.state = this.state;

    return (
      <MyContext.Provider value={this.value}>
        <div className="App">
          <Foo />
          <Bar />
        </div>
      </MyContext.Provider>
    );
  }
}
```

This works normally. It's a convoluted example but the thing being passed via `MyContext`, (`this.value`) is always the same object. Yet everything works as expected (https://codesandbox.io/s/react-passing-same-object-for-value-via-context-8oequ5?file=/src/App.js:0-905)

In my case the object I'm passing via the context is an object for manipulating the state so that any component can do

```

     const stateAPI = useContext(StateContext);
     stateAPI.makeFullScreen();
     stateAPI.stopTheVideo();

```

But because that object is static, whatever is happening in react-tile-pane suddenly things stop working.

I worked around it by always passing a new object so the code above becomes this

```
export default class App extends React.Component {
  constructor() {
    super();

    this.state = { count: 1 };
    // this.value = {
    //  setState: (...args) => this.setState(...args)
    //};
    this.stateSetter = (...args) => this.setState(...args);
  }
  render() {
//    this.value.state = this.state;

    return (
//      <MyContext.Provider value={this.value}>
      <MyContext.Provider value={{state: this.state, setState: this.stateSetter}}>
        <div className="App">
          <Foo />
          <Bar />
        </div>
      </MyContext.Provider>
    );
  }
}
```

that only took me about 20 hrs to find 😅

**Comment by greggman** [comment]
So just going to throw this out there. Maybe memoizing doesn't belong in react-tile-pane? If things go too slow, the user can momoize themsevles.

```
const Arbutus = React.memo(function Arbutus() {
  const [number, count] = useContext(counterContext);
  return (
    <div onClick={() => count((n) => n + 1)} style={paneStyle}>
      {number} catties of arbutus
    </div>
  );
})

const Apple = React.memo(function Apple() {
  return <div style={paneStyle}>apple</div>;
});
```

Then at least things work as expected, all components render, and the user can opt into memoization. Just a thought.

**Comment by xcfox** [comment]
`memoizing` is a fairly common optimization in React, and is well suited to `react-tile-pane`.
When it comes to complex state management, I feel that state management tools are necessary.
I recommend using [valtio](https://github.com/pmndrs/valtio) to manage complex data in your project, it's perfect for managing objectified state, much simpler than React Context and saves me a lot of time.
I think you'll like the way valtio updates the data:
```jsx
export const state = proxy({
  count: 0,
  name: 'foo',
  inc() {
    ++this.count
  },
  setName(name) {
    this.name = name
  },
})

function Counter() {
  const snap = useSnapshot(state)
  return (
    <div>
      {snap.count}
      <button onClick={() => state.inc()}>+1</button>
    </div>
  )
}
```

**Comment by greggman** [comment]
I agree memoization is common. It'd just be nice if the user was in control, not the library, so the user can choose when to memoize and when not to memoize. As it, code that works, stops working when react-tile-pane is put in the middle.
